[[protocols]]
internal = true
role-types = ["GennaroDKGBls381"]

[[protocols]]
internal = true
role-types = ["DfnsCGGMP21Secp256k1", "DfnsCGGMP21Secp256r1", "DfnsCGGMP21Stark"]

[[protocols]]
internal = true
role-types = ["WstsV2"]

[[protocols]]
internal = true
role-types = ["ZcashFrostEd25519", "ZcashFrostEd448", "ZcashFrostP256", "ZcashFrostP384", "ZcashFrostSecp256k1", "ZcashFrostRistretto255"]

[[protocols]]
internal = true
role-types = ["ZkSaaSGroth16"]

[[protocols]]
internal = false
repository = { git = "https://github.com/webb-tools/silent-shard-dkls23-gadget" }
role-types = ["SilentShardDKLS23Secp256k1"]
bin-hashes = { linux-x86_64="SomeHash", darwin-x86_64="SomeOtherHash" }
