[package]
name = "aggregator-blueprint"
version = "0.1.0"
edition = "2021"
description = "A blueprint defining an Aggregator service, useful for Tangle AVS Contexts"
license = "Unlicense"
homepage = "https://tangle.tools"
repository = "https://github.com/webb-tools/tangle-avs-blueprint"
readme = "README.md"
categories = ["cryptography", "cryptography::cryptocurrencies", "tangle-blueprint"]
keywords = ["tangle", "blueprint", "avs"]
rust-version = "1.79"

[dependencies]
tracing = "0.1"
async-trait = "0.1"

color-eyre = "0.6"
tokio = { version = "1.39", default-features = false, features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["parking_lot", "env-filter"] }

gadget-sdk = { workspace = true, features = ["std"] }
#eigensdk-rs = { workspace = true }

[build-dependencies]
blueprint-metadata = "0.1"
